# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

intToBinary <- function(x, head) {
    .Call('_knapsack_intToBinary', PACKAGE = 'knapsack', x, head)
}

